# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="${loader_version_range}"
license='${mod_license}'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="TeamStarry, BeclR0Ck"
authors="${mod_authors}"
logoFile="crystaldream_icon.png"
description='''${mod_description}'''

[[mixins]]
config="crystaldream.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
